FROM node:12
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install && mv node_modules ../

# FYI: This is a workaround for the fact that npm only recognizes
#      binaries at $(cwd)/node_modules/.bin
ENV PATH=/usr/src/node_modules/.bin:${PATH}

VOLUME ["/usr/src/app"]
EXPOSE 3000

CMD npm run start
