FROM node:12
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install && mv node_modules ../
VOLUME ["/usr/src/app"]
EXPOSE 3000

CMD npm run start
