version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app/

    environment:
      NODE_ENV: development

    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app
    environment:
      NODE_ENV: development

    ports:
      - 5000:3000
