FROM node:12
WORKDIR /usr/src/app

RUN chown -R node: /usr/src && \
    npm install -g pm2 && \
    apt update && \
    apt install -y \
      vim less && \
    rm -rf /var/lib/apt/lists/*

USER node
VOLUME ["/usr/src/app"]
EXPOSE 3000

CMD npm install && npx pm2-dev start ./ecosystem.config.js